server:
  port: 7001
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: INFO
    com.bsolz.microservices: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
management.health.circuitbreakers.emabled: true
management.zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans
management.tracing.sampling.probability: 1.0
---
spring:
  application.name: product
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://localhost:8888
    username: ${CONFIG_SERVER_USR}
    password: ${CONFIG_SERVER_PWD}
  config:
    activate:
      on-profile: docker
spring.data.mongodb.host: mongodb

server:
  port: 8080
