server:
  port: 7001
logging:
  level:
    root: INFO
    com.bsolz.microservices: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    stream:
      bindings:
        messageProcessor-in-0:
          destination: products
          group: productsGroup
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
            partitioned: true
            instance-index: 0
      rabbit:
        bindings:
          messageProcessor-in-0.consumer:
            autoBindDlq: true
            republishToDlq: true
      kafka:
        bindings:
          messageProcessor-in-0:
            consumer:
              enableDlq: true
spring.data.mongodb.host: mongodb



server:
  port: 8080
