server:
  port: 7003
server.error.include-message: always

logging:
  level:
    root: INFO
    com.bsolz: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  data:
    jpa:
      hibernate:
        ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: pwd
    hikari:
      initializationFailTimeout: 60000

---
spring:
  config:
    activate:
      on-profile: docker
spring.datasource:
  url: jdbc:mysql://mysql/review-db
server.port: 8080
